### ISSUE TITLE
Core dump on startup

### ISSUE THREAD

**Issue by zmyrgel** [TurningWheel/Barony#444]
Barony crashes on startup on OpenBSD. Once it hits "loading items" the console shows segfault and soon after core dumps:

```
tmy@asteroid .barony $ /usr/local/bin/barony-bin -datadir=$HOME/.barony 
[12-23-43] Data path is /home/tmy/.barony
[12-23-43] Output path is /home/tmy/.barony
Caught segfault at address 0xffffffffffffffe8
Abort trap (core dumped) 
```

Here's bt from core file.

```
(gdb) bt
#0  thrkill () at -:3
#1  0x00000636548ab4ae in _libc_abort () at /usr/src/lib/libc/stdlib/abort.c:51
#2  0x0000063654883176 in wrterror (d=0x63676f24580, msg=0x636548279ef "bogus pointer (double free?) %p") at /usr/src/lib/libc/stdlib/malloc.c:300
#3  0x0000063654886359 in findpool (p=0xdbdbdbdbdbdbdbdb, argpool=<optimized out>, foundpool=0x7f7fffff2ec0, saved_function=0x7f7fffff2ec8) at /usr/src/lib/libc/stdlib/malloc.c:1355
#4  0x000006365488348a in ofree (argpool=0x7f7fffff2f20, p=0xdbdbdbdbdbdbdbdb, clear=0, check=0, argsz=0) at /usr/src/lib/libc/stdlib/malloc.c:1369
#5  0x00000636548833c0 in free (ptr=0xdbdbdbdbdbdbdbdb) at /usr/src/lib/libc/stdlib/malloc.c:1488
#6  0x000006343001624f in std::__1::vector<std::__1::vector<int, std::__1::allocator<int> >, std::__1::allocator<std::__1::vector<int, std::__1::allocator<int> > > >::~vector() ()
#7  0x00000636548da15d in _libc___cxa_finalize (dso=<optimized out>) at /usr/src/lib/libc/stdlib/atexit.c:177
#8  0x00000636548c2161 in _libc_exit (status=0) at /usr/src/lib/libc/stdlib/exit.c:54
#9  0x000006343006f4fa in segfault_sigaction(int, siginfo_t*, void*) ()
#10 0x000006368f2cf005 in ?? ()
#11 0x0000000000000005 in ?? ()
#12 0x0000063654827913 in ?? () from /usr/lib/libc.so.96.0
#13 0x00000636548e8890 in ?? () from /usr/lib/libc.so.96.0
#14 0x00000636548e7338 in malloc_lock () from /usr/lib/libc.so.96.0
#15 0x00000636548e8890 in ?? () from /usr/lib/libc.so.96.0
#16 0x0000000000006dc0 in ?? ()
#17 0x0000000000007fff in ?? ()
#18 0xe76194cedccc7897 in ?? ()
#19 0x00007f7fffff36d0 in ?? ()
#20 0x00000634302f7c88 in items ()
#21 0x00000634302f7ec0 in classStatGrowth ()
#22 0x0000063719c7cb40 in ?? ()
#23 0x00007f7fffff3890 in ?? ()
#24 0xffffffffffffffe8 in ?? ()
#25 0x0000000000000000 in ?? ()
(gdb) quit
```

**Comment by devnexen** [comment]
Barony releases are tied to specific assets. I see OpenBSD is 3.2.2 and maybe you re trying to use with 3.3.0 assets ?

**Comment by zmyrgel** [comment]
Hmm, could be.

I'm using the latest assets from gog, i think they were 3.2.3 hotfix installer. Quick look didn't yield Link to get older versionsa.

Timo

**Comment by namtsui** [comment]
> Barony releases are tied to specific assets. I see OpenBSD is 3.2.2 and maybe you re trying to use with 3.3.0 assets ?

Thanks for the hint.

I was getting the same segfault after loading items on OpenBSD. Updating the openbsd port to 3.3.6-rc1 works with the epic game store version.

The package README mentions:
> The game version should exactly match the package version
